# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180226_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='client_id',
            field=models.CharField(max_length=127, unique=True, verbose_name='client_id'),
        ),
    ]
